# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/merhaba/merhaba.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==merhaba || ORIG_REF_NAME==merhaba} -quiet] -quiet

# IP: bd/merhaba/ip/merhaba_processing_system7_0_0/merhaba_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==merhaba_processing_system7_0_0 || ORIG_REF_NAME==merhaba_processing_system7_0_0} -quiet] -quiet

# XDC: bd/merhaba/merhaba_ooc.xdc
